# Generated by Django 3.1.2 on 2020-12-30 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userAuth',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=100)),
                ('userPassWord', models.CharField(max_length=20)),
            ],
        ),
    ]
